version: '3'
services:
  mysql:
    container_name: gopicture_db
    image: mysql:latest
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
  app:
    build: .
    image: gopicture-image
    container_name: gopicturel
    ports:
      - 8888:8888
    environment:
      GO_ENV: dev
    volumes:
      - ./:/app
    links:
      - mysql
