version: '3'
services:
  mysql:
    container_name: gopicture_db
    image: mysql:latest
    restart: always
    env_file: ./envfiles/docker.env
    ports:
      - 3306:3306
  app:
    build: .
    image: gopicture-image
    container_name: gopicturel
    ports:
      - 8888:8888
    environment:
      GO_ENV: dev
    volumes:
      - ./:/app
    links:
      - mysql
